POST http://localhost:3003/api/blogs
Content-Type: application/json 
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3R1c2VyIiwiaWQiOiI2MGVjNjYwNGRhOTVlMDY5MjhmODA3YjUiLCJpYXQiOjE2MjYxMDU4MDIsImV4cCI6MTYyNjEwOTQwMn0.u29x031t6H52ZRZbExRnlwosxV_2qrQcCglrHlLT85M

{
  "title": "Test blog1",
  "author": "Test Author",
  "url": "http://localhost/testurl",
  "likes": 2
}