DELETE http://localhost:3003/api/blogs/60ec7eba7d57ea776fd52f03
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3R1c2VyIiwiaWQiOiI2MGVjNjYwNGRhOTVlMDY5MjhmODA3YjUiLCJpYXQiOjE2MjYxMTAxMTUsImV4cCI6MTYyNjExMzcxNX0.ajy-_allmOA_Px8ATXE1MTaiUZzscfnDasTzheM7vtM